apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-app-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: payment-app-k8s-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: payment-app-secret