apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - name: test
    image: nginx
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: payment-app-k8s-secret
          key: DB_USERNAME

    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: payment-app-k8s-secret
          key: DB_PASSWORD

    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: payment-app-k8s-secret
          key: JWT_SECRET
  restartPolicy: Never