name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run Tests
        run: mvn test

      - name: Build Jar
        run: mvn clean package